// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");

Jest.describe("some test", (function (param) {
        return Jest.test("passes!", (function (param) {
                      return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](true));
                    }));
      }));

/*  Not a pure module */
