// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var PolygoneModel = require("./polygoneModel.bs.js");
var PolynomialPage = require("./polynomialPage.bs.js");

function App(Props) {
  var match = React.useReducer(PolygoneModel.State[/* reducer */1], PolygoneModel.State[/* initial_state */0]);
  var state = match[0];
  return React.createElement("div", {
              className: "container-fluid"
            }, React.createElement("div", {
                  className: "row"
                }, React.createElement("div", {
                      className: "col-md-2"
                    }, "Sidecar"), React.createElement("div", {
                      className: "col-md-9"
                    }, React.createElement(PolynomialPage.Page[/* make */1], {
                          state: state,
                          dispatch: match[1]
                        })), React.createElement("div", {
                      className: "col-md-1"
                    }, String(state[/* dimensions */3]), React.createElement("br", undefined), String(state[/* degree */4]))));
}

var make = App;

exports.make = make;
/* react Not a pure module */
