// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var maxDimensions = 5;

var maxDegree = 9;

exports.maxDimensions = maxDimensions;
exports.maxDegree = maxDegree;
/* No side effect */
