// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var PolygoneComponents = require("./polygoneComponents.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(PolygoneComponents.App[/* make */0], { }), "app");

/*  Not a pure module */
