// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var App = require("./app.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(App.make, { }), "app");

/*  Not a pure module */
