// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Flavor = /* module */[];

var Polynomial = /* module */[];

var Action = /* module */[];

function reducer(state, action) {
  var new_state;
  switch (action.tag | 0) {
    case 0 : 
        new_state = /* record */[
          /* exponentsArray */action[0],
          /* variablesNotation */state[/* variablesNotation */1],
          /* coefficientNotation */state[/* coefficientNotation */2],
          /* dimensions */state[/* dimensions */3],
          /* degree */state[/* degree */4]
        ];
        break;
    case 1 : 
        new_state = /* record */[
          /* exponentsArray */state[/* exponentsArray */0],
          /* variablesNotation */action[0],
          /* coefficientNotation */state[/* coefficientNotation */2],
          /* dimensions */state[/* dimensions */3],
          /* degree */state[/* degree */4]
        ];
        break;
    case 2 : 
        new_state = /* record */[
          /* exponentsArray */state[/* exponentsArray */0],
          /* variablesNotation */state[/* variablesNotation */1],
          /* coefficientNotation */action[0],
          /* dimensions */state[/* dimensions */3],
          /* degree */state[/* degree */4]
        ];
        break;
    case 3 : 
        new_state = /* record */[
          /* exponentsArray */state[/* exponentsArray */0],
          /* variablesNotation */state[/* variablesNotation */1],
          /* coefficientNotation */state[/* coefficientNotation */2],
          /* dimensions */action[0],
          /* degree */state[/* degree */4]
        ];
        break;
    case 4 : 
        new_state = /* record */[
          /* exponentsArray */state[/* exponentsArray */0],
          /* variablesNotation */state[/* variablesNotation */1],
          /* coefficientNotation */state[/* coefficientNotation */2],
          /* dimensions */state[/* dimensions */3],
          /* degree */action[0]
        ];
        break;
    
  }
  console.log(new_state);
  return new_state;
}

var State_000 = /* initial_state : record */[
  /* exponentsArray */"",
  /* variablesNotation : Traditional */0,
  /* coefficientNotation : Pedantic */1,
  /* dimensions */3,
  /* degree */6
];

var State = /* module */[
  State_000,
  /* reducer */reducer
];

exports.Flavor = Flavor;
exports.Polynomial = Polynomial;
exports.Action = Action;
exports.State = State;
/* No side effect */
