// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var PolygoneModel = require("./polygoneModel.bs.js");
var PolynomialPage = require("./polynomialPage.bs.js");

function PolygoneComponents$Task(Props) {
  var task = Props.task;
  var onDone = Props.onDone;
  var match = task[/* status */2];
  return React.createElement("li", {
              className: match ? "done" : "pending"
            }, React.createElement("button", {
                  title: "done",
                  onClick: (function (param) {
                      return Curry._1(onDone, task[/* id */0]);
                    })
                }), React.createElement("span", undefined, task[/* label */1]));
}

var Task = /* module */[/* make */PolygoneComponents$Task];

function PolygoneComponents$App(Props) {
  var match = React.useReducer(PolygoneModel.State[/* reducer */1], PolygoneModel.State[/* initial_state */0]);
  var state = match[0];
  var dimensions = String(state[/* dimensions */3]);
  var degree = String(state[/* degree */4]);
  console.log(dimensions);
  console.log(degree);
  return React.createElement("div", {
              className: "container-fluid"
            }, React.createElement("div", {
                  className: "row"
                }, React.createElement("div", {
                      className: "col-md-2"
                    }, "Sidecar"), React.createElement("div", {
                      className: "col-md-9"
                    }, React.createElement(PolynomialPage.Page[/* make */1], {
                          dimensions: dimensions,
                          degree: degree
                        })), React.createElement("div", {
                      className: "col-md-1"
                    }, degree)));
}

var App = /* module */[/* make */PolygoneComponents$App];

exports.Task = Task;
exports.App = App;
/* react Not a pure module */
